# Generated by Django 3.2.16 on 2023-10-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='locations',
            new_name='location',
        ),
    ]
